### ISSUE TITLE
Revision 25 de Marzo

### ISSUE THREAD

**Issue by gera-gpz-itnl** [ceciliahuertam/P2_17100238_Actualizado#1]
## Observaciones

**T1** Resumen Miuy bien, Puntos extra porque usted paso el examen  

**T3** Solo le falto el `charset="utf-8"`  

**T4** Esta tarea era hacer solo un formulario responsivo, no un template de bootstrap ???
y este CopyRight:  `Copyright 2020 Melanie Titus. All Rights Reserved`

**Comment by ceciliahuertam** [comment]
Profe, con respecto a la tarea 4, es de mi proyecto final de equipo,  ya
que mi proyecto es promocionar a una empresa de logistica y el  "
CopyRight: Copyright 2020 Melanie Titus. All Rights Reserved" era solo un
ejemplo, no existe esa referencia si la busca, ya que la invente.

**Comment by gera-gpz-itnl** [comment]
Ok, entonces ese sera su proyecto....solo hay que ver como meter ahi en su página 
de proyecto, una consulta a una base de datos,
El proyecto no es solo hacer una pagina, hay que "pegarle" a una base de datos
Ya corregí su calificación en el excel
